export interface DeepTankSettings {
  separation_weight: number;
  alignment_weight: number;
  cohesion_weight: number;
  wander_strength: number;
  hunger_rate: number;
  mutation_rate_small: number;
  mutation_rate_large: number;
  species_threshold: number;
  day_night_cycle: boolean;
  day_night_speed: number;
  bubble_rate: number;
  current_strength: number;
  auto_feed_enabled: boolean;
  auto_feed_interval: number;
  auto_feed_amount: number;
  ollama_enabled: boolean;
  ollama_url: string;
  ollama_model: string;
  master_volume: number;
  ambient_enabled: boolean;
  event_sounds_enabled: boolean;
  theme: string;
  environmental_events_enabled: boolean;
  event_frequency: number;
  territory_enabled: boolean;
  territory_claim_radius: number;
  disease_enabled: boolean;
  disease_infection_chance: number;
  disease_spontaneous_chance: number;
  disease_duration: number;
  disease_damage: number;
  disease_spread_radius: number;
}

export const defaultSettings: DeepTankSettings = {
  separation_weight: 1.5,
  alignment_weight: 1.0,
  cohesion_weight: 1.0,
  wander_strength: 0.3,
  hunger_rate: 0.0005,
  mutation_rate_small: 0.1,
  mutation_rate_large: 0.02,
  species_threshold: 2.5,
  day_night_cycle: true,
  day_night_speed: 1.0,
  bubble_rate: 1.0,
  current_strength: 0.0,
  auto_feed_enabled: false,
  auto_feed_interval: 600,
  auto_feed_amount: 4,
  ollama_enabled: false,
  ollama_url: "http://localhost:11434",
  ollama_model: "llama3.2",
  master_volume: 0.3,
  ambient_enabled: true,
  event_sounds_enabled: true,
  theme: "aquarium",
  environmental_events_enabled: true,
  event_frequency: 1.0,
  territory_enabled: true,
  territory_claim_radius: 60,
  disease_enabled: false,
  disease_infection_chance: 0.3,
  disease_spontaneous_chance: 0.00005,
  disease_duration: 600,
  disease_damage: 0.0005,
  disease_spread_radius: 40.0,
};
